import Link from "next/link";
import { Upload, Table, Zap, Download, ArrowRight, Github } from "lucide-react";

const codeLines = [
  { num: 1, tokens: [{ text: "// Generated by MCPForge", color: "#8b949e" }] },
  {
    num: 2,
    tokens: [
      { text: "import", color: "#ff7b72" },
      { text: " { McpServer } ", color: "#c9d1d9" },
      { text: "from", color: "#ff7b72" },
      { text: ' "', color: "#c9d1d9" },
      { text: "@modelcontextprotocol/sdk/server/mcp.js", color: "#a5d6ff" },
      { text: '"', color: "#c9d1d9" },
      { text: ";", color: "#c9d1d9" },
    ],
  },
  { num: 3, tokens: [] },
  {
    num: 4,
    tokens: [
      { text: "const", color: "#ff7b72" },
      { text: " server = ", color: "#c9d1d9" },
      { text: "new", color: "#ff7b72" },
      { text: " McpServer({", color: "#c9d1d9" },
    ],
  },
  {
    num: 5,
    tokens: [
      { text: "  name: ", color: "#c9d1d9" },
      { text: '"petstore-api"', color: "#a5d6ff" },
      { text: ",", color: "#c9d1d9" },
    ],
  },
  {
    num: 6,
    tokens: [
      { text: "  version: ", color: "#c9d1d9" },
      { text: '"1.0.0"', color: "#a5d6ff" },
      { text: ",", color: "#c9d1d9" },
    ],
  },
  { num: 7, tokens: [{ text: "});", color: "#c9d1d9" }] },
  { num: 8, tokens: [] },
  {
    num: 9,
    tokens: [
      { text: "server", color: "#c9d1d9" },
      { text: ".", color: "#c9d1d9" },
      { text: "tool", color: "#d2a8ff" },
      { text: "(", color: "#c9d1d9" },
      { text: '"createPet"', color: "#a5d6ff" },
      { text: ", ", color: "#c9d1d9" },
      { text: '"Create a new pet"', color: "#a5d6ff" },
      { text: ", {", color: "#c9d1d9" },
    ],
  },
  {
    num: 10,
    tokens: [
      { text: "  name: { type: ", color: "#c9d1d9" },
      { text: '"string"', color: "#a5d6ff" },
      { text: ", description: ", color: "#c9d1d9" },
      { text: '"Pet name"', color: "#a5d6ff" },
      { text: " },", color: "#c9d1d9" },
    ],
  },
  {
    num: 11,
    tokens: [
      { text: "}, ", color: "#c9d1d9" },
      { text: "async", color: "#ff7b72" },
      { text: " (params) ", color: "#c9d1d9" },
      { text: "=>", color: "#ff7b72" },
      { text: " {", color: "#c9d1d9" },
    ],
  },
  {
    num: 12,
    tokens: [
      { text: "  ", color: "#c9d1d9" },
      { text: "const", color: "#ff7b72" },
      { text: " res = ", color: "#c9d1d9" },
      { text: "await", color: "#ff7b72" },
      { text: " fetch(", color: "#c9d1d9" },
      { text: '"https://api.petstore.com/pets"', color: "#a5d6ff" },
      { text: ", {", color: "#c9d1d9" },
    ],
  },
  {
    num: 13,
    tokens: [
      { text: "    method: ", color: "#c9d1d9" },
      { text: '"POST"', color: "#a5d6ff" },
      { text: ", body: JSON.stringify(params),", color: "#c9d1d9" },
    ],
  },
  { num: 14, tokens: [{ text: "  });", color: "#c9d1d9" }] },
  {
    num: 15,
    tokens: [
      { text: "  ", color: "#c9d1d9" },
      { text: "return", color: "#ff7b72" },
      { text: " { content: [{ type: ", color: "#c9d1d9" },
      { text: '"text"', color: "#a5d6ff" },
      { text: ", text: JSON.stringify(", color: "#c9d1d9" },
      { text: "await", color: "#ff7b72" },
      { text: " res.json()) }] };", color: "#c9d1d9" },
    ],
  },
  { num: 16, tokens: [{ text: "});", color: "#c9d1d9" }] },
  { num: 17, tokens: [] },
  {
    num: 18,
    tokens: [
      { text: "server", color: "#c9d1d9" },
      { text: ".", color: "#c9d1d9" },
      { text: "resource", color: "#d2a8ff" },
      { text: "(", color: "#c9d1d9" },
      { text: '"listPets"', color: "#a5d6ff" },
      { text: ", ", color: "#c9d1d9" },
      { text: '"pets://list"', color: "#a5d6ff" },
      { text: ", ", color: "#c9d1d9" },
      { text: "async", color: "#ff7b72" },
      { text: " (uri) ", color: "#c9d1d9" },
      { text: "=>", color: "#ff7b72" },
      { text: " {", color: "#c9d1d9" },
    ],
  },
  {
    num: 19,
    tokens: [
      { text: "  ", color: "#c9d1d9" },
      { text: "const", color: "#ff7b72" },
      { text: " res = ", color: "#c9d1d9" },
      { text: "await", color: "#ff7b72" },
      { text: " fetch(", color: "#c9d1d9" },
      { text: '"https://api.petstore.com/pets"', color: "#a5d6ff" },
      { text: ");", color: "#c9d1d9" },
    ],
  },
  {
    num: 20,
    tokens: [
      { text: "  ", color: "#c9d1d9" },
      { text: "return", color: "#ff7b72" },
      { text: " { contents: [{ uri, text: JSON.stringify(", color: "#c9d1d9" },
      { text: "await", color: "#ff7b72" },
      { text: " res.json()) }] };", color: "#c9d1d9" },
    ],
  },
  { num: 21, tokens: [{ text: "});", color: "#c9d1d9" }] },
];

const features = [
  {
    icon: Table,
    title: "Visual endpoint mapping",
    description:
      "See every endpoint in your API. Assign MCP types with dropdowns, not config files.",
  },
  {
    icon: Zap,
    title: "Smart defaults",
    description:
      "GET routes become Resources. Mutations become Tools. Override anything.",
  },
  {
    icon: Download,
    title: "Download and run",
    description:
      "One zip file. npm install, npm start. TypeScript MCP server ready to go.",
  },
];

const steps = [
  {
    num: "1",
    title: "Upload spec",
    description: "JSON or YAML. Paste, upload, or fetch from URL.",
  },
  {
    num: "2",
    title: "Review endpoints",
    description: "Table view with method badges, params, and descriptions.",
  },
  {
    num: "3",
    title: "Configure server",
    description: "Transport, auth, port. All with live preview.",
  },
  {
    num: "4",
    title: "Download project",
    description: "Complete TypeScript MCP server in a zip.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#0d1117]">
      {/* Nav */}
      <nav className="border-b border-[#30363d]">
        <div className="mx-auto flex h-14 max-w-[1100px] items-center justify-between px-4 md:px-6">
          <span className="text-[15px] font-semibold text-[#c9d1d9]">
            MCPForge
          </span>
          <div className="flex items-center gap-3">
            <Link
              href="/auth/signin"
              className="text-[14px] text-[#8b949e] hover:text-[#c9d1d9]"
            >
              Sign in
            </Link>
            <Link
              href="/auth/signup"
              className="rounded-md bg-[#238636] px-3 py-1.5 text-[14px] font-medium text-white hover:bg-[#2ea043]"
            >
              Get started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="px-4 pt-24 pb-20 md:px-6">
        <div className="mx-auto max-w-[1100px]">
          <div className="mx-auto max-w-[600px] text-center">
            <h1 className="text-[32px] font-semibold leading-tight text-white">
              OpenAPI to MCP server, visually
            </h1>
            <p className="mt-4 text-[16px] leading-relaxed text-[#8b949e]">
              Upload an OpenAPI spec. Map endpoints to tools and resources.
              Download a production-ready MCP server.
            </p>
            <div className="mt-8 flex items-center justify-center gap-3">
              <Link
                href="/auth/signup"
                className="inline-flex items-center rounded-md bg-[#238636] px-4 py-2 text-[14px] font-medium text-white hover:bg-[#2ea043]"
              >
                Get started
                <ArrowRight className="ml-1.5 h-4 w-4" />
              </Link>
              <a
                href="https://github.com/nicholasrubright/mcpforge"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center rounded-md border border-[#30363d] bg-[#161b22] px-4 py-2 text-[14px] font-medium text-[#c9d1d9] hover:border-[#8b949e]"
              >
                <Github className="mr-1.5 h-4 w-4" />
                View on GitHub
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Code Preview */}
      <section className="px-4 pb-24 md:px-6">
        <div className="mx-auto max-w-[1100px]">
          <div className="overflow-hidden rounded-md border border-[#30363d] bg-[#161b22]">
            <div className="flex items-center gap-2 border-b border-[#30363d] px-4 py-2.5">
              <span className="h-3 w-3 rounded-full bg-[#30363d]" />
              <span className="h-3 w-3 rounded-full bg-[#30363d]" />
              <span className="h-3 w-3 rounded-full bg-[#30363d]" />
              <span className="ml-2 text-[12px] text-[#8b949e]">
                server.ts
              </span>
            </div>
            <div className="overflow-x-auto p-4">
              <pre className="font-mono text-[13px] leading-[1.6]">
                {codeLines.map((line) => (
                  <div key={line.num} className="flex">
                    <span className="mr-4 inline-block w-5 select-none text-right text-[#30363d]">
                      {line.num}
                    </span>
                    <span>
                      {line.tokens.length === 0 ? (
                        "\n"
                      ) : (
                        line.tokens.map((token, i) => (
                          <span key={i} style={{ color: token.color }}>
                            {token.text}
                          </span>
                        ))
                      )}
                    </span>
                  </div>
                ))}
              </pre>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="border-t border-[#30363d] px-4 py-20 md:px-6">
        <div className="mx-auto grid max-w-[1100px] gap-10 md:grid-cols-3 md:gap-12">
          {features.map((feature) => (
            <div key={feature.title}>
              <feature.icon className="mb-3 h-4 w-4 text-[#58a6ff]" />
              <h3 className="text-[14px] font-medium text-white">
                {feature.title}
              </h3>
              <p className="mt-1 text-[13px] leading-relaxed text-[#8b949e]">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="border-t border-[#30363d] px-4 py-20 md:px-6">
        <div className="mx-auto max-w-[1100px]">
          <h2 className="mb-10 text-[14px] font-medium text-[#8b949e]">
            How it works
          </h2>
          <div className="grid gap-8 md:grid-cols-4 md:gap-10">
            {steps.map((step) => (
              <div key={step.num}>
                <span className="mb-2 block font-mono text-[13px] text-[#58a6ff]">
                  {step.num}
                </span>
                <h3 className="text-[14px] font-medium text-white">
                  {step.title}
                </h3>
                <p className="mt-1 text-[13px] leading-relaxed text-[#8b949e]">
                  {step.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer CTA + Footer */}
      <section className="border-t border-[#30363d] px-4 py-20 md:px-6">
        <div className="mx-auto max-w-[1100px] text-center">
          <p className="text-[16px] text-[#c9d1d9]">
            Start converting your API
          </p>
          <Link
            href="/auth/signup"
            className="mt-4 inline-flex items-center rounded-md bg-[#238636] px-4 py-2 text-[14px] font-medium text-white hover:bg-[#2ea043]"
          >
            Get started
            <ArrowRight className="ml-1.5 h-4 w-4" />
          </Link>
        </div>
      </section>

      <footer className="border-t border-[#30363d] px-4 py-6 md:px-6">
        <div className="mx-auto flex max-w-[1100px] items-center justify-between">
          <span className="text-[13px] text-[#8b949e]">MCPForge</span>
          <a
            href="https://github.com/nicholasrubright/mcpforge"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[13px] text-[#8b949e] hover:text-[#c9d1d9]"
          >
            GitHub
          </a>
        </div>
      </footer>
    </div>
  );
}
